FROM ubuntu:18.04
#
# Run UUCP server in container
#
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew vim-tiny bash curl wget git uucp rmail bsd-mailx

RUN chsh news -s /bin/bash

EXPOSE 540

USER uucp
CMD /usr/lib/uucp/uucico -1
