FROM ubuntu:18.04
#
# Run UUCP server in container
#
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew vim-tiny bash curl wget git uucp rmail bsd-mailx xinetd

COPY service.uucp /xinetd.conf

RUN chsh uucp -s /bin/bash

EXPOSE 540

# USER uucp
# CMD /usr/lib/uucp/uucico
CMD xinetd  -pidfile /run/xinetd.pid -dontfork -f /xinetd.conf
