on: 
  push: 
    paths: 
    - 'Dockerfile.inn'
name: Build & Push Dockerfile.inn
jobs:
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: /Dockerfile.inn
          repository: gnuu/inn
          tags: latest
