on: 
  push: 
    paths: 
    - 'Dockerfile.innuucp'
name: Build & Push Dockerfile.innuucp
jobs:
  deploy:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.innuucp
          repository: gnuu/innuucp
          tags: latest
